version: '3'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    environment:
      - TZ=Europe/Rome
    networks:
      - poli
    ports:
      - 1883:1883
    restart: unless-stopped
  gps:
    build: ./gps
    container_name: gps
    restart: unless-stopped
    devices:
      - "/dev/ttyAMA1:/dev/ttyAMA1"
    networks:
      - poli
    depends_on:
      - "mqtt-broker"
  gear:
    build: ./gear
    container_name: gear
    restart: unless-stopped
    devices:
      - "/dev/ttyS0:/dev/ttyS0"
    networks:
      - poli
    depends_on:
      - "mqtt-broker"
  video:
    build: ./video
    container_name: video
    restart: unless-stopped
    devices:
      - "/dev/:/dev/"
    volumes:
      - "/opt/vc:/opt/vc"
    environment:
      - "LD_LIBRARY_PATH=/opt/vc/lib"
      - "READTHEDOCS=True"
    networks:
      - poli
    privileged: true
    depends_on:
      - "mqtt-broker"
  ant:
    build: ./ant
    container_name: ant
    restart: unless-stopped
    privileged: true
    devices:
      - "/dev/:/dev/"
    networks:
      - poli
    depends_on:
      - "mqtt-broker"
  messages:
    build: ./messages
    container_name: messages
    restart: unless-stopped
    networks:
      - poli
    depends_on:
      - "mqtt-broker"
  manager:
    build: ./manager
    container_name: manager
    restart: unless-stopped
    privileged: true
    networks:
      - poli
    depends_on:
      - "mqtt-broker"

#  bt:
#    build: ./bt
#    container_name: bt
#    restart: unless-stopped
#    privileged: true
#    networks:
#      - poli
#    depends_on:
#      - "mqtt-broker"

  communication:
    build: ./communication
    container_name: communication
    restart: unless-stopped
    networks:
      - poli
    depends_on:
      - "mqtt-broker"

networks:
  poli:
    external: false