version: '3'

services:

  mqtt-broker:
    image: eclipse-mosquitto:1.6.14
    container_name: mqtt-broker
    environment:
      - TZ=Europe/Rome
    networks:
      - poli
    ports:
      - 1883:1883
    restart: unless-stopped

networks:
  poli:
    external: false