version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto
    network_mode: host
    container_name: mosquitto
    volumes:
      - ./mosquitto:/mosquitto
    # environment:
    #   - TZ=Europe/Rome
    ports:
      - 1883:1883
    restart: always
