name: CI

on:
  push:
    branches: [dev-refactoring]
  pull_request:
    branches: [dev-refactoring]
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]
        poetry-version: [1.1.14]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test module `ant` on arm
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: https://downloads.raspberrypi.org/raspios_oldstable_armhf/images/raspios_oldstable_armhf-2022-04-07/2022-04-04-raspios-buster-armhf.img.xz
          commands: |
            cd modules/ant
            apt-get update --fix-missing
            apt-get install -y --no-install-recommends python3-dev python3-setuptools python3-wheel python3-pip git $(cat package_list.txt)
            pip3 install poetry 
            poetry install
            poetry run pytest


      # Errore di `RPi.GPIO` da aggiustare prima di abilitare la CI
      #
      # - name: Test module `video` on arm
      #   uses: pguyot/arm-runner-action@v2
      #   with:
      #     base_image: https://downloads.raspberrypi.org/raspios_oldstable_armhf/images/raspios_oldstable_armhf-2022-04-07/2022-04-04-raspios-buster-armhf.img.xz
      #     commands: |
      #       cd modules/video
      #       apt-get update --fix-missing
      #       apt-get install -y --no-install-recommends python3-dev python3-setuptools python3-wheel python3-pip git $(cat package_list.txt)
      #       pip3 install -r requirements.txt
      #       pip3 install RPi.GPIO
      #       pip3 install pytest
      #       pytest

      - name: Test module `accelerometer` on arm
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: https://downloads.raspberrypi.org/raspios_oldstable_armhf/images/raspios_oldstable_armhf-2022-04-07/2022-04-04-raspios-buster-armhf.img.xz
          commands: |
            cd modules/accelerometer
            apt-get update --fix-missing
            apt-get install -y --no-install-recommends python3-dev python3-setuptools python3-wheel python3-pip git $(cat package_list.txt)
            pip3 install poetry 
            poetry install
            poetry run pytest
