name: CI

on:
  push:
    branches: [main, dev-refactoring]
  pull_request:
    branches: [main, dev-refactoring]
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]
        poetry-version: [1.1.14]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test module `video` on arm
        uses: pguyot/arm-runner-action@v1
        with:
          commands: |
            cd modules/video
            apt-get update --fix-missing
            apt-get install -y --no-install-recommends python3-dev python3-setuptools python3-wheel python3-pip git $(cat package_list.txt)
            pip3 install -r requirements.txt 
            pip3 install pytest
            pytest
